const random=Math.floor(Math.random()*100+1)
const userInput=document.getElementById('guessField')
const submit=document.getElementById('submit')
const guessSlot=document.getElementsByClassName('guesses')
const remaining=document.getElementsByClassName('lastResult')
const lowOrHigh=document.getElementsByClassName('lowOrHigh')
const startOver=document.getElementsByClassName('result')
